#!/bin/bash
set -e

echo "==> Setting up C++ Build Environment for Trading Core from Repository Root..."

# Check if Conan or CMake is installed globally or in current env
if ! command -v conan &> /dev/null || ! command -v cmake &> /dev/null; then
    echo "==> Missing Conan or CMake in PATH. Setting up a local Python virtual environment..."
    
    # Create venv if it doesn't exist
    if [ ! -d ".venv" ]; then
        python3 -m venv .venv
    fi
    
    # Activate venv
    source .venv/bin/activate
    
    # Install conan, cmake, and ninja inside the venv
    echo "==> Installing Conan, CMake, and Ninja in virtual environment..."
    pip3 install conan cmake ninja
else
    echo "==> Conan and CMake found in PATH."
fi

echo "==> Creating default Conan profile if it doesn't exist..."
conan profile detect --force || true
# Fix for macOS apple-clang 21.0 not being in the default conan settings.yml
sed -i.bak 's/compiler.version=21/compiler.version=15.0/g' ~/.conan2/profiles/default || true

# We no longer wipe the CMake cache so that incremental builds are blazing fast!
# If you ever need a clean build, manually run: rm -rf build/CMakeCache.txt build/CMakeFiles

# Install dependencies using Conan
echo "==> Installing dependencies via Conan..."
conan install trading-core --output-folder=build --build=missing -c tools.cmake.cmaketoolchain:generator=Ninja

# Configure and Build using CMake presets generated by Conan
echo "==> Configuring CMake..."
cmake --preset conan-release -S trading-core

echo "==> Building trading-core..."
cmake --build build --config Release

echo "==> Build successful! Executable is at build/trading-core"
